<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Obj;

class DeepSkyObjectsSeeder extends Seeder
{
    public function run()
    {
        $objects = [
            // Messier Objects
            ['name' => 'Crab Nebula', 'catalog' => 'M1', 'type' => 'Supernova Remnant', 'description' => 'The Crab Nebula is a supernova remnant and pulsar wind nebula in the constellation of Taurus.'],
            ['name' => 'Globular Cluster M2', 'catalog' => 'M2', 'type' => 'Globular Cluster', 'description' => 'M2 is a globular cluster in the constellation Aquarius.'],
            ['name' => 'Globular Cluster M3', 'catalog' => 'M3', 'type' => 'Globular Cluster', 'description' => 'M3 is a globular cluster in the constellation Canes Venatici.'],
            ['name' => 'Globular Cluster M4', 'catalog' => 'M4', 'type' => 'Globular Cluster', 'description' => 'M4 is a globular cluster in the constellation Scorpius.'],
            ['name' => 'Rose Cluster', 'catalog' => 'M5', 'type' => 'Globular Cluster', 'description' => 'M5 is a globular cluster in the constellation Serpens.'],
            ['name' => 'Butterfly Cluster', 'catalog' => 'M6', 'type' => 'Open Cluster', 'description' => 'M6 is an open cluster in the constellation Scorpius.'],
            ['name' => 'Ptolemy\'s Cluster', 'catalog' => 'M7', 'type' => 'Open Cluster', 'description' => 'M7 is an open cluster in the constellation Scorpius.'],
            ['name' => 'Lagoon Nebula', 'catalog' => 'M8', 'type' => 'Emission Nebula', 'description' => 'The Lagoon Nebula is a giant interstellar cloud in the constellation Sagittarius.'],
            ['name' => 'Globular Cluster M9', 'catalog' => 'M9', 'type' => 'Globular Cluster', 'description' => 'M9 is a globular cluster in the constellation Ophiuchus.'],
            ['name' => 'Globular Cluster M10', 'catalog' => 'M10', 'type' => 'Globular Cluster', 'description' => 'M10 is a globular cluster in the constellation Ophiuchus.'],
            ['name' => 'Wild Duck Cluster', 'catalog' => 'M11', 'type' => 'Open Cluster', 'description' => 'M11 is an open cluster in the constellation Scutum.'],
            ['name' => 'Gumball Globular', 'catalog' => 'M12', 'type' => 'Globular Cluster', 'description' => 'M12 is a globular cluster in the constellation Ophiuchus.'],
            ['name' => 'Hercules Globular Cluster', 'catalog' => 'M13', 'type' => 'Globular Cluster', 'description' => 'M13 is a globular cluster in the constellation Hercules.'],
            ['name' => 'Double Cluster in Hercules', 'catalog' => 'M14', 'type' => 'Globular Cluster', 'description' => 'M14 is a globular cluster in the constellation Ophiuchus.'],
            ['name' => 'Great Pegasus Cluster', 'catalog' => 'M15', 'type' => 'Globular Cluster', 'description' => 'M15 is a globular cluster in the constellation Pegasus.'],
            ['name' => 'Eagle Nebula', 'catalog' => 'M16', 'type' => 'Emission Nebula', 'description' => 'The Eagle Nebula is a young open cluster of stars in the constellation Serpens.'],
            ['name' => 'Omega Nebula', 'catalog' => 'M17', 'type' => 'Emission Nebula', 'description' => 'The Omega Nebula is an H II region in the constellation Sagittarius.'],
            ['name' => 'Black Swan Cluster', 'catalog' => 'M18', 'type' => 'Open Cluster', 'description' => 'M18 is an open cluster in the constellation Sagittarius.'],
            ['name' => 'Globular Cluster M19', 'catalog' => 'M19', 'type' => 'Globular Cluster', 'description' => 'M19 is a globular cluster in the constellation Ophiuchus.'],
            ['name' => 'Trifid Nebula', 'catalog' => 'M20', 'type' => 'Emission Nebula', 'description' => 'The Trifid Nebula is an H II region in the constellation Sagittarius.'],
            ['name' => 'Webb\'s Cross', 'catalog' => 'M21', 'type' => 'Open Cluster', 'description' => 'M21 is an open cluster in the constellation Sagittarius.'],
            ['name' => 'Sagittarius Cluster', 'catalog' => 'M22', 'type' => 'Globular Cluster', 'description' => 'M22 is a globular cluster in the constellation Sagittarius.'],
            ['name' => 'Open Cluster M23', 'catalog' => 'M23', 'type' => 'Open Cluster', 'description' => 'M23 is an open cluster in the constellation Sagittarius.'],
            ['name' => 'Small Sagittarius Star Cloud', 'catalog' => 'M24', 'type' => 'Star Cloud', 'description' => 'M24 is a star cloud in the constellation Sagittarius.'],
            ['name' => 'Open Cluster M25', 'catalog' => 'M25', 'type' => 'Open Cluster', 'description' => 'M25 is an open cluster in the constellation Sagittarius.'],
            ['name' => 'Open Cluster M26', 'catalog' => 'M26', 'type' => 'Open Cluster', 'description' => 'M26 is an open cluster in the constellation Scutum.'],
            ['name' => 'Dumbbell Nebula', 'catalog' => 'M27', 'type' => 'Planetary Nebula', 'description' => 'The Dumbbell Nebula is a planetary nebula in the constellation Vulpecula.'],
            ['name' => 'Globular Cluster M28', 'catalog' => 'M28', 'type' => 'Globular Cluster', 'description' => 'M28 is a globular cluster in the constellation Sagittarius.'],
            ['name' => 'Cooling Tower', 'catalog' => 'M29', 'type' => 'Open Cluster', 'description' => 'M29 is an open cluster in the constellation Cygnus.'],
            ['name' => 'Jellyfish Cluster', 'catalog' => 'M30', 'type' => 'Globular Cluster', 'description' => 'M30 is a globular cluster in the constellation Capricornus.'],
            ['name' => 'Andromeda Galaxy', 'catalog' => 'M31', 'type' => 'Spiral Galaxy', 'description' => 'The Andromeda Galaxy is a barred spiral galaxy approximately 2.5 million light-years from Earth.'],
            ['name' => 'Le Gentil', 'catalog' => 'M32', 'type' => 'Dwarf Elliptical Galaxy', 'description' => 'M32 is a dwarf elliptical galaxy in the constellation Andromeda.'],
            ['name' => 'Triangulum Galaxy', 'catalog' => 'M33', 'type' => 'Spiral Galaxy', 'description' => 'The Triangulum Galaxy is a spiral galaxy 2.73 million light-years from Earth.'],
            ['name' => 'Spiral Galaxy M34', 'catalog' => 'M34', 'type' => 'Open Cluster', 'description' => 'M34 is an open cluster in the constellation Perseus.'],
            ['name' => 'Open Cluster M35', 'catalog' => 'M35', 'type' => 'Open Cluster', 'description' => 'M35 is an open cluster in the constellation Gemini.'],
            ['name' => 'Pinwheel Cluster', 'catalog' => 'M36', 'type' => 'Open Cluster', 'description' => 'M36 is an open cluster in the constellation Auriga.'],
            ['name' => 'Salt and Pepper Cluster', 'catalog' => 'M37', 'type' => 'Open Cluster', 'description' => 'M37 is an open cluster in the constellation Auriga.'],
            ['name' => 'Starfish Cluster', 'catalog' => 'M38', 'type' => 'Open Cluster', 'description' => 'M38 is an open cluster in the constellation Auriga.'],
            ['name' => 'Open Cluster M39', 'catalog' => 'M39', 'type' => 'Open Cluster', 'description' => 'M39 is an open cluster in the constellation Cygnus.'],
            ['name' => 'Winnecke 4', 'catalog' => 'M40', 'type' => 'Double Star', 'description' => 'M40 is a double star in the constellation Ursa Major.'],
            ['name' => 'Little Beehive Cluster', 'catalog' => 'M41', 'type' => 'Open Cluster', 'description' => 'M41 is an open cluster in the constellation Canis Major.'],
            ['name' => 'Orion Nebula', 'catalog' => 'M42', 'type' => 'Emission Nebula', 'description' => 'The Orion Nebula is a diffuse nebula situated in the Milky Way, being south of Orion\'s Belt.'],
            ['name' => 'De Mairan\'s Nebula', 'catalog' => 'M43', 'type' => 'Emission Nebula', 'description' => 'M43 is a star-forming region in the constellation Orion.'],
            ['name' => 'Beehive Cluster', 'catalog' => 'M44', 'type' => 'Open Cluster', 'description' => 'The Beehive Cluster is an open cluster in the constellation Cancer.'],
            ['name' => 'Pleiades', 'catalog' => 'M45', 'type' => 'Open Cluster', 'description' => 'The Pleiades is an open star cluster in the constellation Taurus.'],
            ['name' => 'Open Cluster M46', 'catalog' => 'M46', 'type' => 'Open Cluster', 'description' => 'M46 is an open cluster in the constellation Puppis.'],
            ['name' => 'Open Cluster M47', 'catalog' => 'M47', 'type' => 'Open Cluster', 'description' => 'M47 is an open cluster in the constellation Puppis.'],
            ['name' => 'Open Cluster M48', 'catalog' => 'M48', 'type' => 'Open Cluster', 'description' => 'M48 is an open cluster in the constellation Hydra.'],
            ['name' => 'Elliptical Galaxy M49', 'catalog' => 'M49', 'type' => 'Elliptical Galaxy', 'description' => 'M49 is an elliptical galaxy in the constellation Virgo.'],
            ['name' => 'Heart-Shaped Cluster', 'catalog' => 'M50', 'type' => 'Open Cluster', 'description' => 'M50 is an open cluster in the constellation Monoceros.'],
            ['name' => 'Whirlpool Galaxy', 'catalog' => 'M51', 'type' => 'Spiral Galaxy', 'description' => 'The Whirlpool Galaxy is an interacting grand-design spiral galaxy.'],
            ['name' => 'Scorpion', 'catalog' => 'M52', 'type' => 'Open Cluster', 'description' => 'M52 is an open cluster in the constellation Cassiopeia.'],
            ['name' => 'Globular Cluster M53', 'catalog' => 'M53', 'type' => 'Globular Cluster', 'description' => 'M53 is a globular cluster in the constellation Coma Berenices.'],
            ['name' => 'Globular Cluster M54', 'catalog' => 'M54', 'type' => 'Globular Cluster', 'description' => 'M54 is a globular cluster in the constellation Sagittarius.'],
            ['name' => 'Spectre', 'catalog' => 'M55', 'type' => 'Globular Cluster', 'description' => 'M55 is a globular cluster in the constellation Sagittarius.'],
            ['name' => 'Globular Cluster M56', 'catalog' => 'M56', 'type' => 'Globular Cluster', 'description' => 'M56 is a globular cluster in the constellation Lyra.'],
            ['name' => 'Ring Nebula', 'catalog' => 'M57', 'type' => 'Planetary Nebula', 'description' => 'The Ring Nebula is a planetary nebula in the constellation Lyra.'],
            ['name' => 'Spiral Galaxy M58', 'catalog' => 'M58', 'type' => 'Barred Spiral Galaxy', 'description' => 'M58 is a barred spiral galaxy in the constellation Virgo.'],
            ['name' => 'Elliptical Galaxy M59', 'catalog' => 'M59', 'type' => 'Elliptical Galaxy', 'description' => 'M59 is an elliptical galaxy in the constellation Virgo.'],
            ['name' => 'Elliptical Galaxy M60', 'catalog' => 'M60', 'type' => 'Elliptical Galaxy', 'description' => 'M60 is an elliptical galaxy in the constellation Virgo.'],
            ['name' => 'Spiral Galaxy M61', 'catalog' => 'M61', 'type' => 'Barred Spiral Galaxy', 'description' => 'M61 is a barred spiral galaxy in the constellation Virgo.'],
            ['name' => 'Globular Cluster M62', 'catalog' => 'M62', 'type' => 'Globular Cluster', 'description' => 'M62 is a globular cluster in the constellation Ophiuchus.'],
            ['name' => 'Sunflower Galaxy', 'catalog' => 'M63', 'type' => 'Spiral Galaxy', 'description' => 'The Sunflower Galaxy is a spiral galaxy in the constellation Canes Venatici.'],
            ['name' => 'Black Eye Galaxy', 'catalog' => 'M64', 'type' => 'Spiral Galaxy', 'description' => 'The Black Eye Galaxy is a spiral galaxy in the constellation Coma Berenices.'],
            ['name' => 'Leo Triplet Member M65', 'catalog' => 'M65', 'type' => 'Spiral Galaxy', 'description' => 'M65 is a spiral galaxy in the constellation Leo.'],
            ['name' => 'Leo Triplet Member M66', 'catalog' => 'M66', 'type' => 'Spiral Galaxy', 'description' => 'M66 is a spiral galaxy in the constellation Leo.'],
            ['name' => 'King Cobra', 'catalog' => 'M67', 'type' => 'Open Cluster', 'description' => 'M67 is an open cluster in the constellation Cancer.'],
            ['name' => 'Globular Cluster M68', 'catalog' => 'M68', 'type' => 'Globular Cluster', 'description' => 'M68 is a globular cluster in the constellation Hydra.'],
            ['name' => 'Globular Cluster M69', 'catalog' => 'M69', 'type' => 'Globular Cluster', 'description' => 'M69 is a globular cluster in the constellation Sagittarius.'],
            ['name' => 'Globular Cluster M70', 'catalog' => 'M70', 'type' => 'Globular Cluster', 'description' => 'M70 is a globular cluster in the constellation Sagittarius.'],
            ['name' => 'Globular Cluster M71', 'catalog' => 'M71', 'type' => 'Globular Cluster', 'description' => 'M71 is a globular cluster in the constellation Sagitta.'],
            ['name' => 'Globular Cluster M72', 'catalog' => 'M72', 'type' => 'Globular Cluster', 'description' => 'M72 is a globular cluster in the constellation Aquarius.'],
            ['name' => 'Aquarius Dwarf', 'catalog' => 'M73', 'type' => 'Asterism', 'description' => 'M73 is an asterism in the constellation Aquarius.'],
            ['name' => 'Phantom Galaxy', 'catalog' => 'M74', 'type' => 'Spiral Galaxy', 'description' => 'The Phantom Galaxy is a spiral galaxy in the constellation Pisces.'],
            ['name' => 'Globular Cluster M75', 'catalog' => 'M75', 'type' => 'Globular Cluster', 'description' => 'M75 is a globular cluster in the constellation Sagittarius.'],
            ['name' => 'Little Dumbbell Nebula', 'catalog' => 'M76', 'type' => 'Planetary Nebula', 'description' => 'The Little Dumbbell Nebula is a planetary nebula in the constellation Perseus.'],
            ['name' => 'Cetus A', 'catalog' => 'M77', 'type' => 'Barred Spiral Galaxy', 'description' => 'M77 is a barred spiral galaxy in the constellation Cetus.'],
            ['name' => 'Diffuse Nebula M78', 'catalog' => 'M78', 'type' => 'Reflection Nebula', 'description' => 'M78 is a reflection nebula in the constellation Orion.'],
            ['name' => 'Globular Cluster M79', 'catalog' => 'M79', 'type' => 'Globular Cluster', 'description' => 'M79 is a globular cluster in the constellation Lepus.'],
            ['name' => 'Globular Cluster M80', 'catalog' => 'M80', 'type' => 'Globular Cluster', 'description' => 'M80 is a globular cluster in the constellation Scorpius.'],
            ['name' => 'Bode\'s Galaxy', 'catalog' => 'M81', 'type' => 'Spiral Galaxy', 'description' => 'Bode\'s Galaxy is a spiral galaxy in the constellation Ursa Major.'],
            ['name' => 'Cigar Galaxy', 'catalog' => 'M82', 'type' => 'Starburst Galaxy', 'description' => 'The Cigar Galaxy is a starburst galaxy in the constellation Ursa Major.'],
            ['name' => 'Southern Pinwheel Galaxy', 'catalog' => 'M83', 'type' => 'Barred Spiral Galaxy', 'description' => 'The Southern Pinwheel Galaxy is a barred spiral galaxy in the constellation Hydra.'],
            ['name' => 'Elliptical Galaxy M84', 'catalog' => 'M84', 'type' => 'Elliptical Galaxy', 'description' => 'M84 is an elliptical galaxy in the constellation Virgo.'],
            ['name' => 'Elliptical Galaxy M85', 'catalog' => 'M85', 'type' => 'Elliptical Galaxy', 'description' => 'M85 is an elliptical galaxy in the constellation Coma Berenices.'],
            ['name' => 'Elliptical Galaxy M86', 'catalog' => 'M86', 'type' => 'Elliptical Galaxy', 'description' => 'M86 is an elliptical galaxy in the constellation Virgo.'],
            ['name' => 'Virgo A', 'catalog' => 'M87', 'type' => 'Elliptical Galaxy', 'description' => 'M87 is a supergiant elliptical galaxy in the constellation Virgo.'],
            ['name' => 'Spiral Galaxy M88', 'catalog' => 'M88', 'type' => 'Spiral Galaxy', 'description' => 'M88 is a spiral galaxy in the constellation Coma Berenices.'],
            ['name' => 'Elliptical Galaxy M89', 'catalog' => 'M89', 'type' => 'Elliptical Galaxy', 'description' => 'M89 is an elliptical galaxy in the constellation Virgo.'],
            ['name' => 'Spiral Galaxy M90', 'catalog' => 'M90', 'type' => 'Spiral Galaxy', 'description' => 'M90 is a spiral galaxy in the constellation Virgo.'],
            ['name' => 'Barred Spiral Galaxy M91', 'catalog' => 'M91', 'type' => 'Barred Spiral Galaxy', 'description' => 'M91 is a barred spiral galaxy in the constellation Coma Berenices.'],
            ['name' => 'Globular Cluster M92', 'catalog' => 'M92', 'type' => 'Globular Cluster', 'description' => 'M92 is a globular cluster in the constellation Hercules.'],
            ['name' => 'Open Cluster M93', 'catalog' => 'M93', 'type' => 'Open Cluster', 'description' => 'M93 is an open cluster in the constellation Puppis.'],
            ['name' => 'Croc\'s Eye Galaxy', 'catalog' => 'M94', 'type' => 'Spiral Galaxy', 'description' => 'M94 is a spiral galaxy in the constellation Canes Venatici.'],
            ['name' => 'Barred Spiral Galaxy M95', 'catalog' => 'M95', 'type' => 'Barred Spiral Galaxy', 'description' => 'M95 is a barred spiral galaxy in the constellation Leo.'],
            ['name' => 'Spiral Galaxy M96', 'catalog' => 'M96', 'type' => 'Spiral Galaxy', 'description' => 'M96 is a spiral galaxy in the constellation Leo.'],
            ['name' => 'Owl Nebula', 'catalog' => 'M97', 'type' => 'Planetary Nebula', 'description' => 'The Owl Nebula is a planetary nebula in the constellation Ursa Major.'],
            ['name' => 'Spiral Galaxy M98', 'catalog' => 'M98', 'type' => 'Spiral Galaxy', 'description' => 'M98 is a spiral galaxy in the constellation Coma Berenices.'],
            ['name' => 'Spiral Galaxy M99', 'catalog' => 'M99', 'type' => 'Spiral Galaxy', 'description' => 'M99 is a spiral galaxy in the constellation Coma Berenices.'],
            ['name' => 'Spiral Galaxy M100', 'catalog' => 'M100', 'type' => 'Spiral Galaxy', 'description' => 'M100 is a spiral galaxy in the constellation Coma Berenices.'],
            ['name' => 'Pinwheel Galaxy', 'catalog' => 'M101', 'type' => 'Spiral Galaxy', 'description' => 'The Pinwheel Galaxy is a face-on spiral galaxy in the constellation Ursa Major.'],
            ['name' => 'Spindle Galaxy', 'catalog' => 'M102', 'type' => 'Lenticular Galaxy', 'description' => 'M102 is a lenticular galaxy in the constellation Draco.'],
            ['name' => 'Open Cluster M103', 'catalog' => 'M103', 'type' => 'Open Cluster', 'description' => 'M103 is an open cluster in the constellation Cassiopeia.'],
            ['name' => 'Sombrero Galaxy', 'catalog' => 'M104', 'type' => 'Spiral Galaxy', 'description' => 'The Sombrero Galaxy is a spiral galaxy in the constellation Virgo.'],
            ['name' => 'Elliptical Galaxy M105', 'catalog' => 'M105', 'type' => 'Elliptical Galaxy', 'description' => 'M105 is an elliptical galaxy in the constellation Leo.'],
            ['name' => 'Spiral Galaxy M106', 'catalog' => 'M106', 'type' => 'Spiral Galaxy', 'description' => 'M106 is a spiral galaxy in the constellation Canes Venatici.'],
            ['name' => 'Globular Cluster M107', 'catalog' => 'M107', 'type' => 'Globular Cluster', 'description' => 'M107 is a globular cluster in the constellation Ophiuchus.'],
            ['name' => 'Surfboard Galaxy', 'catalog' => 'M108', 'type' => 'Barred Spiral Galaxy', 'description' => 'M108 is a barred spiral galaxy in the constellation Ursa Major.'],
            ['name' => 'Barred Spiral Galaxy M109', 'catalog' => 'M109', 'type' => 'Barred Spiral Galaxy', 'description' => 'M109 is a barred spiral galaxy in the constellation Ursa Major.'],
            ['name' => 'Dwarf Elliptical Galaxy M110', 'catalog' => 'M110', 'type' => 'Dwarf Elliptical Galaxy', 'description' => 'M110 is a dwarf elliptical galaxy in the constellation Andromeda.'],

            // Popular NGC Objects
            ['name' => 'Rosette Nebula', 'catalog' => 'NGC 2237', 'type' => 'Emission Nebula', 'description' => 'The Rosette Nebula is a vast emission nebula located in the Monoceros constellation.'],
            ['name' => 'Cone Nebula', 'catalog' => 'NGC 2264', 'type' => 'Nebula', 'description' => 'The Cone Nebula is an H II region in the constellation of Monoceros.'],
            ['name' => 'California Nebula', 'catalog' => 'NGC 1499', 'type' => 'Emission Nebula', 'description' => 'The California Nebula is an emission nebula located in the constellation Perseus.'],
            ['name' => 'North America Nebula', 'catalog' => 'NGC 7000', 'type' => 'Emission Nebula', 'description' => 'The North America Nebula is an emission nebula in the constellation Cygnus.'],
            ['name' => 'Veil Nebula', 'catalog' => 'NGC 6960', 'type' => 'Supernova Remnant', 'description' => 'The Veil Nebula is a cloud of heated and ionized gas and dust in the constellation Cygnus.'],
            ['name' => 'Helix Nebula', 'catalog' => 'NGC 7293', 'type' => 'Planetary Nebula', 'description' => 'The Helix Nebula is a planetary nebula located in the constellation Aquarius.'],
            ['name' => 'Horsehead Nebula', 'catalog' => 'Barnard 33', 'type' => 'Dark Nebula', 'description' => 'The Horsehead Nebula is a dark nebula in the constellation Orion.'],
            ['name' => 'Flame Nebula', 'catalog' => 'NGC 2024', 'type' => 'Emission Nebula', 'description' => 'The Flame Nebula is an emission nebula in the constellation Orion.'],
            ['name' => 'Tarantula Nebula', 'catalog' => 'NGC 2070', 'type' => 'Emission Nebula', 'description' => 'The Tarantula Nebula is an H II region in the Large Magellanic Cloud.'],
            ['name' => 'Carina Nebula', 'catalog' => 'NGC 3372', 'type' => 'Nebula', 'description' => 'The Carina Nebula is a complex area of bright and dark nebulosity in the constellation Carina.'],
            ['name' => 'Sculptor Galaxy', 'catalog' => 'NGC 253', 'type' => 'Intermediate Spiral Galaxy', 'description' => 'The Sculptor Galaxy is an intermediate spiral galaxy in the constellation Sculptor.'],
            ['name' => 'Centaurus A', 'catalog' => 'NGC 5128', 'type' => 'Lenticular Galaxy', 'description' => 'Centaurus A is a galaxy in the constellation of Centaurus.'],
            ['name' => 'Needle Galaxy', 'catalog' => 'NGC 4565', 'type' => 'Spiral Galaxy', 'description' => 'The Needle Galaxy is an edge-on spiral galaxy in the constellation Coma Berenices.'],

            // More Northern Hemisphere Objects (Caldwell & NGC)
            ['name' => 'Bow Tie Nebula', 'catalog' => 'NGC 40', 'type' => 'Planetary Nebula', 'description' => 'A planetary nebula in Cepheus.'],
            ['name' => 'Blue Snowball Nebula', 'catalog' => 'NGC 7662', 'type' => 'Planetary Nebula', 'description' => 'A planetary nebula in Andromeda.'],
            ['name' => 'Blinking Planetary', 'catalog' => 'NGC 6826', 'type' => 'Planetary Nebula', 'description' => 'A planetary nebula in Cygnus.'],
            ['name' => 'Crescent Nebula', 'catalog' => 'NGC 6888', 'type' => 'Emission Nebula', 'description' => 'An emission nebula in Cygnus.'],
            ['name' => 'Bubble Nebula', 'catalog' => 'NGC 7635', 'type' => 'Emission Nebula', 'description' => 'An emission nebula in Cassiopeia.'],
            ['name' => 'Cat\'s Eye Nebula', 'catalog' => 'NGC 6543', 'type' => 'Planetary Nebula', 'description' => 'A planetary nebula in Draco.'],
            ['name' => 'Saturn Nebula', 'catalog' => 'NGC 7009', 'type' => 'Planetary Nebula', 'description' => 'A planetary nebula in Aquarius.'],
            ['name' => 'Deer Lick Group', 'catalog' => 'NGC 7331', 'type' => 'Spiral Galaxy', 'description' => 'A spiral galaxy in Pegasus.'],
            ['name' => 'Silver Splinter', 'catalog' => 'NGC 891', 'type' => 'Spiral Galaxy', 'description' => 'An edge-on spiral galaxy in Andromeda.'],
            ['name' => 'Cocoon Nebula', 'catalog' => 'IC 5146', 'type' => 'Reflection/Emission Nebula', 'description' => 'A nebula in Cygnus.'],
            ['name' => 'Elephant\'s Trunk Nebula', 'catalog' => 'IC 1396', 'type' => 'Emission Nebula', 'description' => 'A concentration of interstellar gas and dust in Cepheus.'],
            ['name' => 'Heart Nebula', 'catalog' => 'IC 1805', 'type' => 'Emission Nebula', 'description' => 'An emission nebula in Cassiopeia.'],
            ['name' => 'Soul Nebula', 'catalog' => 'IC 1848', 'type' => 'Emission Nebula', 'description' => 'An emission nebula in Cassiopeia.'],
            ['name' => 'Pacman Nebula', 'catalog' => 'NGC 281', 'type' => 'Emission Nebula', 'description' => 'An H II region in Cassiopeia.'],
            ['name' => 'Wizard Nebula', 'catalog' => 'NGC 7380', 'type' => 'Open Cluster+Nebula', 'description' => 'An open cluster and nebula in Cepheus.'],
            ['name' => 'Iris Nebula', 'catalog' => 'NGC 7023', 'type' => 'Reflection Nebula', 'description' => 'A reflection nebula in Cepheus.'],
            ['name' => 'Jellyfish Nebula', 'catalog' => 'IC 443', 'type' => 'Supernova Remnant', 'description' => 'A supernova remnant in Gemini.'],
            ['name' => 'Monkey Head Nebula', 'catalog' => 'NGC 2174', 'type' => 'Emission Nebula', 'description' => 'An emission nebula in Orion.'],
            ['name' => 'Christmas Tree Cluster', 'catalog' => 'NGC 2264', 'type' => 'Open Cluster', 'description' => 'Includes the Cone Nebula in Monoceros.'],
            ['name' => 'Hubble\'s Variable Nebula', 'catalog' => 'NGC 2261', 'type' => 'Reflection Nebula', 'description' => 'A variable nebula in Monoceros.'],
            ['name' => 'Whale Galaxy', 'catalog' => 'NGC 4631', 'type' => 'Spiral Galaxy', 'description' => 'An edge-on spiral galaxy in Canes Venatici.'],
            ['name' => 'Hockey Stick Galaxy', 'catalog' => 'NGC 4656', 'type' => 'Irr Galaxy', 'description' => 'An irregular galaxy in Canes Venatici.'],
            ['name' => 'Black Eye Galaxy', 'catalog' => 'M64', 'type' => 'Spiral Galaxy', 'description' => 'A spiral galaxy in Coma Berenices.'],
        ];

        foreach ($objects as $obj) {
            Obj::updateOrCreate(
            ['name' => $obj['name'], 'catalog' => $obj['catalog']],
                $obj
            );
        }
    }
}
