<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ObjectController;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\CompareController;
use App\Http\Controllers\Admin\UserController as AdminUserController;
use App\Http\Controllers\Admin\ImageController as AdminImageController;
use App\Http\Controllers\Admin\NewsController as AdminNewsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/

Route::get('/', [ObjectController::class, 'home'])->name('home');
Route::get('/board', [ObjectController::class, 'board'])->name('board');
Route::get('/objects/{id}', [ObjectController::class, 'show'])->name('objects.show');
Route::get('/api/user/{id}/images', [ObjectController::class, 'userImages']);

Route::middleware(['auth'])->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::post('/profile', [ProfileController::class, 'update'])->name('profile.update');

    // Normal user upload routes (path: /upload)
    Route::get('/upload', [ImageController::class, 'create'])->name('images.create');
    Route::post('/upload', [ImageController::class, 'store'])->name('images.store');

    Route::get('/compare/{objectId}', [CompareController::class, 'show'])->name('compare.show');

    // Dashboard view for logged-in users
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
});

/*
 | Include authentication routes (generated by Breeze / Laravel UI)
*/
if (file_exists(__DIR__ . '/auth.php')) {
    require __DIR__ . '/auth.php';
}

/*
 | Admin routes (prefix admin, name admin.*, protected by is_admin)
*/
Route::prefix('admin')->name('admin.')->middleware(['auth','is_admin'])->group(function () {
    Route::get('/', function(){ return redirect()->route('admin.users.index'); });

   // users (admin)
Route::get('/users', [AdminUserController::class,'index'])->name('users.index');
Route::get('/users/create', [AdminUserController::class,'create'])->name('users.create');   // neu
Route::post('/users', [AdminUserController::class,'store'])->name('users.store');           // neu
Route::get('/users/{user}/edit', [AdminUserController::class,'edit'])->name('users.edit');
Route::put('/users/{user}', [AdminUserController::class,'update'])->name('users.update');
Route::delete('/users/{user}', [AdminUserController::class,'destroy'])->name('users.destroy');


    // images (admin)
    Route::get('/images', [AdminImageController::class,'index'])->name('images.index');
    Route::get('/images/create', [AdminImageController::class,'create'])->name('images.create');
    Route::post('/images', [AdminImageController::class,'store'])->name('images.store');
    Route::get('/images/{image}/edit', [AdminImageController::class,'edit'])->name('images.edit');
    Route::put('/images/{image}', [AdminImageController::class,'update'])->name('images.update');
    Route::delete('/images/{image}', [AdminImageController::class,'destroy'])->name('images.destroy');
    Route::post('/images/{image}/approve', [AdminImageController::class,'approve'])->name('images.approve');

    // news (admin) - resource style
    Route::resource('news', AdminNewsController::class)->names([
        'index' => 'news.index',
        'create' => 'news.create',
        'store' => 'news.store',
        'edit' => 'news.edit',
        'update' => 'news.update',
        'destroy' => 'news.destroy',
        'show' => 'news.show',
    ]);
});
