<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ObjectController;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\CompareController;
use App\Http\Controllers\Admin\UserController as AdminUserController;
use App\Http\Controllers\Admin\ImageController as AdminImageController;
use App\Http\Controllers\Admin\NewsController as AdminNewsController;

/* |-------------------------------------------------------------------------- | Web Routes |-------------------------------------------------------------------------- */

Route::get('/', [ObjectController::class , 'home'])->name('home');
Route::get('/board', [ObjectController::class , 'board'])->name('board');
Route::get('/objects/{id}', [ObjectController::class , 'show'])->name('objects.show');
Route::get('/api/user/{id}/images', [ObjectController::class , 'userImages']);
Route::get('lang/{locale}', [App\Http\Controllers\LanguageController::class , 'switch'])->name('lang.switch');

Route::middleware(['auth'])->group(function () {
    // Routes accessible to unverified users
    Route::get('/user/{id}', [ProfileController::class , 'show'])->name('profile.show');

    // Dashboard view for logged-in users (view only)
    Route::get('/dashboard', function () {
            return view('dashboard');
        }
        )->name('dashboard');

        // Routes requiring email verification
        Route::middleware(['verified'])->group(function () {
            Route::get('/profile', [ProfileController::class , 'edit'])->name('profile.edit');
            Route::post('/profile', [ProfileController::class , 'update'])->name('profile.update');

            // Normal user upload routes (path: /upload)
            Route::get('/upload', [ImageController::class , 'create'])->name('images.create');
            Route::post('/upload', [ImageController::class , 'store'])->name('images.store');
            Route::delete('/images/{image}', [ImageController::class , 'destroy'])->name('images.destroy');

            Route::get('/compare/{objectId}', [CompareController::class , 'show'])->name('compare.show');
        }
        );

        // Messaging Routes
        Route::get('/messages', [\App\Http\Controllers\MessageController::class , 'index'])->name('messages.index');
        Route::get('/messages/{user}', [\App\Http\Controllers\MessageController::class , 'show'])->name('messages.show');
        Route::post('/messages', [\App\Http\Controllers\MessageController::class , 'store'])->name('messages.store');
    });

/*
 | Include authentication routes (generated by Breeze / Laravel UI) */
if (file_exists(__DIR__ . '/auth.php')) {
    require __DIR__ . '/auth.php';
}

/*
 | Admin routes (prefix admin, name admin.*, protected by is_admin) */
Route::prefix('admin')->name('admin.')->middleware(['auth', 'is_admin'])->group(function () {
    Route::get('/', function () {
            return redirect()->route('admin.users.index');
        }
        );

        // users (admin)
        Route::get('/users', [AdminUserController::class , 'index'])->name('users.index');
        Route::get('/users/create', [AdminUserController::class , 'create'])->name('users.create');
        Route::post('/users', [AdminUserController::class , 'store'])->name('users.store');
        Route::get('/users/{user}/edit', [AdminUserController::class , 'edit'])->name('users.edit');
        Route::put('/users/{user}', [AdminUserController::class , 'update'])->name('users.update');
        Route::delete('/users/{user}', [AdminUserController::class , 'destroy'])->name('users.destroy');


        // images (admin)
        Route::get('/images', [AdminImageController::class , 'index'])->name('images.index');
        Route::get('/images/create', [AdminImageController::class , 'create'])->name('images.create');
        Route::post('/images', [AdminImageController::class , 'store'])->name('images.store');
        Route::get('/images/{image}/edit', [AdminImageController::class , 'edit'])->name('images.edit');
        Route::put('/images/{image}', [AdminImageController::class , 'update'])->name('images.update');
        Route::delete('/images/{image}', [AdminImageController::class , 'destroy'])->name('images.destroy');
        Route::post('/images/{image}/approve', [AdminImageController::class , 'approve'])->name('images.approve');

        // news (admin) - resource style
        Route::resource('news', AdminNewsController::class)->names([
            'index' => 'news.index',
            'create' => 'news.create',
            'store' => 'news.store',
            'edit' => 'news.edit',
            'update' => 'news.update',
            'destroy' => 'news.destroy',
            'show' => 'news.show',
        ]);

        // changelogs (admin)
        Route::resource('changelogs', \App\Http\Controllers\Admin\ChangelogController::class)->names([
            'index' => 'changelogs.index',
            'create' => 'changelogs.create',
            'store' => 'changelogs.store',
            'edit' => 'changelogs.edit',
            'update' => 'changelogs.update',
            'destroy' => 'changelogs.destroy',
            'show' => 'changelogs.show',
        ]);

        // settings (admin)
        Route::get('/discord', [\App\Http\Controllers\Admin\DiscordController::class , 'index'])->name('discord.index');
        Route::post('/discord', [\App\Http\Controllers\Admin\DiscordController::class , 'update'])->name('discord.update');
        Route::post('/discord/test', [\App\Http\Controllers\Admin\DiscordController::class , 'test'])->name('discord.test');

        Route::get('/settings', [\App\Http\Controllers\Admin\SettingController::class , 'index'])->name('settings.index');
        Route::post('/settings', [\App\Http\Controllers\Admin\SettingController::class , 'update'])->name('settings.update');
        Route::post('/settings', [\App\Http\Controllers\Admin\SettingController::class , 'update'])->name('settings.update');
        Route::post('/settings/sync-objects', [\App\Http\Controllers\Admin\SettingController::class , 'syncObjects'])->name('settings.sync_objects');
        Route::post('/settings/test', [\App\Http\Controllers\Admin\SettingController::class , 'sendTestEmail'])->name('settings.test');

        // Forum Categories (admin)
        Route::resource('forum/categories', \App\Http\Controllers\Admin\ForumCategoryController::class)->names([
            'index' => 'forum.categories.index',
            'create' => 'forum.categories.create',
            'store' => 'forum.categories.store',
            'show' => 'forum.categories.show',
            'edit' => 'forum.categories.edit',
            'update' => 'forum.categories.update',
            'destroy' => 'forum.categories.destroy',
        ]);

        // Backups
        Route::get('backups', [\App\Http\Controllers\Admin\BackupController::class , 'index'])->name('backups.index');
        Route::post('backups', [\App\Http\Controllers\Admin\BackupController::class , 'store'])->name('backups.store');
        Route::get('backups/{filename}', [\App\Http\Controllers\Admin\BackupController::class , 'download'])->name('backups.download');
        Route::delete('backups/{filename}', [\App\Http\Controllers\Admin\BackupController::class , 'destroy'])->name('backups.destroy');

        // Deep Sky Objects
        Route::resource('objects', \App\Http\Controllers\Admin\DeepSkyObjectController::class);
    });

/*
 | Moderation routes (prefix admin/moderation, name admin.moderation.*, protected by is_moderator) */
Route::prefix('admin/moderation')->name('admin.moderation.')->middleware(['auth', 'is_moderator'])->group(function () {
    Route::get('/', [\App\Http\Controllers\Admin\ModerationController::class , 'index'])->name('index');
    Route::post('/{image}/approve', [\App\Http\Controllers\Admin\ModerationController::class , 'approve'])->name('approve');
    Route::post('/{image}/reject', [\App\Http\Controllers\Admin\ModerationController::class , 'reject'])->name('reject');
});
// Moderator/Admin actions on users
Route::middleware(['auth', 'is_admin'])->prefix('admin/users')->name('admin.users.')->group(function () {
    Route::post('/{user}/toggle-moderator', [AdminUserController::class , 'toggleModerator'])->name('toggle-moderator');
    Route::post('/{user}/verify', [AdminUserController::class , 'verifyEmail'])->name('verify');
    Route::post('/{user}/ban', [AdminUserController::class , 'ban'])->name('ban');
    Route::post('/{user}/unban', [AdminUserController::class , 'unban'])->name('unban');
});

// Community Routes (Auth required)
Route::middleware(['auth', 'verified'])->prefix('community')->name('community.')->group(function () {
    Route::get('/', [App\Http\Controllers\CommunityController::class , 'index'])->name('index');
    Route::post('/posts', [App\Http\Controllers\CommunityController::class , 'store'])->name('posts.store'); // Changed to /posts
    Route::post('/{post}/comment', [App\Http\Controllers\CommunityController::class , 'storeComment'])->name('comments.store');
    Route::delete('/{post}', [App\Http\Controllers\CommunityController::class , 'destroy'])->name('posts.destroy'); // Named posts.destroy
    Route::delete('/comments/{comment}', [App\Http\Controllers\CommunityController::class , 'destroyComment'])->name('comments.destroy');

    // Forum Routes
    Route::prefix('forum')->name('forum.')->group(function () {
            Route::get('/', [\App\Http\Controllers\ForumController::class , 'index'])->name('index');
            Route::get('/category/{category}', [\App\Http\Controllers\ForumController::class , 'category'])->name('category');
            Route::get('/category/{category}/create', [\App\Http\Controllers\ForumController::class , 'createThread'])->name('create');
            Route::post('/category/{category}', [\App\Http\Controllers\ForumController::class , 'storeThread'])->name('store');
            Route::get('/thread/{thread}', [\App\Http\Controllers\ForumController::class , 'thread'])->name('thread');
            Route::post('/thread/{thread}/reply', [\App\Http\Controllers\ForumController::class , 'storePost'])->name('post.store');
            Route::delete('/thread/{thread}', [\App\Http\Controllers\ForumController::class , 'destroyThread'])->name('thread.destroy');
            Route::delete('/post/{post}', [\App\Http\Controllers\ForumController::class , 'destroyPost'])->name('post.destroy');
        }
        );
    });

// Groups Routes
// Groups Routes
Route::middleware(['auth', 'verified'])->group(function () {
    // Groups managed by CommunityController
    Route::get('community/groups/create', [\App\Http\Controllers\CommunityController::class , 'createGroup'])->name('community.groups.create');
    Route::post('community/groups', [\App\Http\Controllers\CommunityController::class , 'storeGroup'])->name('community.groups.store');
    Route::get('community/groups/{group}', [\App\Http\Controllers\CommunityController::class , 'showGroup'])->name('community.groups.show');
    Route::post('community/groups/{group}/join', [\App\Http\Controllers\CommunityController::class , 'joinGroup'])->name('community.groups.join');
    Route::post('community/groups/{group}/leave', [\App\Http\Controllers\CommunityController::class , 'leaveGroup'])->name('community.groups.leave');
    Route::post('community/groups/{group}/approve/{user}', [\App\Http\Controllers\CommunityController::class , 'approveRequest'])->name('community.groups.approve');
    Route::post('community/groups/{group}/reject/{user}', [\App\Http\Controllers\CommunityController::class , 'rejectRequest'])->name('community.groups.reject');
    Route::post('community/groups/{group}/remove/{user}', [\App\Http\Controllers\CommunityController::class , 'removeMember'])->name('community.groups.remove');
});

// Admin Community Route
Route::middleware(['auth', 'is_admin'])->prefix('admin/community')->name('admin.community.')->group(function () {
    Route::get('/', [App\Http\Controllers\Admin\CommunityController::class , 'index'])->name('index');
    Route::delete('/{post}', [App\Http\Controllers\Admin\CommunityController::class , 'destroy'])->name('destroy');
});

// Admin Groups Route
Route::middleware(['auth', 'is_admin'])->prefix('admin/groups')->name('admin.groups.')->group(function () {
    Route::get('/', [\App\Http\Controllers\Admin\GroupController::class , 'index'])->name('index');
    Route::delete('/{group}', [\App\Http\Controllers\Admin\GroupController::class , 'destroy'])->name('destroy');
});
